version: "3"
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_DATABASE: sheriff
      MYSQL_USER: sheriff_user
      MYSQL_PASSWORD: sherif123123
    ports:
      - "3306:3306"
    volumes:
      - "./docker-vol/db/data:/var/lib/mysql"